config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :path_prefix => 'd'
  #defining the root url for the website
  root 'pages#index'

  get 'pages/show'

  get 'pages/new'

  get 'pages/create'

  get 'pages/edit'

  get 'pages/update'

  get 'pages/destroy'

  get '/user/:id' => 'users#index'

  get '/user/:id' => 'adminsongs#index'

  get '/user/:id' => 'songs#show'

  #get '/stories' => 'stories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

resources :users

#adding like option routes for songs
resources :songs do
  member do
    post 'like'
  end
end

#adding routes for comments to the songs
resources :songs do
  resources :comments
end
#adding routes for comments to comments
resources :comments do
  resources :comments
end

#resources :pages

resources :stories

#adding like option routes to the images
resources :galleries do
  member do
    post 'imagelike'
  end
end

resources :galleries do
  resources :imagecomments
end

resources :imagecomments do
  resources :imagecomments
end

resources :posts

resources :admins

resources :adminsongs

resources :adminstories

resources :adminimages

resources :aboutpages

resources :helppages

resources :termspages

resources :adspages

resources :statuspages

resources :cookiepages

resources :infopages

resources :gaboutpages

resources :ghelppages




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aboutpage.rb
class Aboutpage < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/adspage.rb
class Adspage < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable

	#belongs_to :user
	#belongs_to :song
	#validates :user_id, presence: true
	validates :content, presence: true
	#validates :song_id, presence: true
	default_scope -> { order(created_at: :desc) } #newest comments to be displayed first

end

app/models/cookiepage.rb
class Cookiepage < ApplicationRecord
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord

  has_attached_file :gallery_image, styles: { medium: "200x200"}
  validates_attachment_content_type :gallery_image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest image to be displayed first

  has_many :imagecomments, dependent: :destroy, as: :commentable
  has_many :imagelikes, dependent: :destroy


  def image_thumbs_up_total
    self.imagelikes.where(imagelike: true).size
  end
  
  def image_thumbs_down_total
    self.imagelikes.where(imagelike: false).size    
  end

end

app/models/helppage.rb
class Helppage < ApplicationRecord
  belongs_to :user
end

app/models/imagecomment.rb
class Imagecomment < ApplicationRecord

	belongs_to :commentable, polymorphic: true
	has_many :imagecomments, as: :commentable

	#belongs_to :user
	#belongs_to :song
	#validates :user_id, presence: true
	validates :content, presence: true
	#validates :song_id, presence: true
	default_scope -> { order(created_at: :desc) } #newest comments to be displayed first

end

app/models/imagelike.rb
class Imagelike < ApplicationRecord
  belongs_to :user
  belongs_to :gallery

  validates_uniqueness_of :user, scope: :gallery 

end

app/models/infopage.rb
class Infopage < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :song

  validates_uniqueness_of :user, scope: :song

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest songs to be displayed first

  has_many :comments, dependent: :destroy, as: :commentable
  has_many :likes, dependent: :destroy

  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end

end

app/models/statuspage.rb
class Statuspage < ApplicationRecord
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  
  #adding the paperclip dependencies to the stories page in order to upload images to the stories
  has_attached_file :story_image, styles: { large: "600x600>", medium: "300x300", thumb: "100x100>" }
  validates_attachment_content_type :story_image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest story to be displayed first


end

app/models/termspage.rb
class Termspage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :user_image, styles: { medium: "200x200", thumb: "85x85>" }
         validates_attachment_content_type :user_image, content_type: /\Aimage\/.*\z/

         has_attached_file :profile_image, styles: { medium: "200x200", thumb: "85x85>" }
         validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\z/

         validates :description, presence: true, length: { maximum: 140 }

         has_many :songs, dependent: :destroy # remove a user's posts if his account is deleted.
         has_many :stories, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :galleries, dependent: :destroy
         has_many :imagelikes, dependent: :destroy


         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower

         # helper methods
         
         # follow another user
         def follow(other)
           active_relationships.create(followed_id: other.id)
         end
         
         # unfollow a user
         def unfollow(other)
           active_relationships.find_by(followed_id: other.id).destroy
         end
         
         # is following a user?
         def following?(other)
           following.include?(other)
         end
end

app/controllers/statuspages_controller.rb
class StatuspagesController < ApplicationController

  before_action :require_login, only: [:index, :new, :create, :edit, :update, :destroy, :show, :like]

  before_action :admin_user, only: [:show, :new, :create, :edit, :update, :destroy, :like]
  
  def index
    @statuses = Statuspage.all
  end

  def show
  end

  def new
    @status = Statuspage.new
  end

  def create
    @status = Statuspage.new(status_params)
    @status.user_id = current_user.id
    respond_to do |f|
      if(@status.save)
        f.html {redirect_to "/statuspages", notice: "Status created!"}
      else
        f.html {redirect_to "/statuspages/new", notice: "Error: Status not saved!"}
      end
    end
  end

  def edit
    @status = Statuspage.find(params[:id])
  end

  def update
    @status = Statuspage.find(params[:id])
    if @status.update(status_params)
      redirect_to statuspage_path(@status)
    else
      render :edit
    end
  end

  def destroy
    Statuspage.find(params[:id]).destroy
    redirect_to statuspages_path
  end

  private

    def status_params #allows certain data to be passed via form
      params.require(:statuspage).permit(:user_id, :title, :content)
    end

    def admin_user
      redirect_to posts_path unless current_user.admin?
    end

    def require_login
      if !user_signed_in?
          redirect_to root_path
      end
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/statuspages_helper.rb
module StatuspagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/statuspages/create.html.erb
<h1>Statuspages#create</h1>
<p>Find me in app/views/statuspages/create.html.erb</p>

app/views/statuspages/destroy.html.erb
<h1>Statuspages#destroy</h1>
<p>Find me in app/views/statuspages/destroy.html.erb</p>

app/views/statuspages/edit.html.erb
<%= form_for(@status) do |f| %>
 
    <!---->
<div class="row">
    <div class="col-12">
      <p>
      <h3>Edit Status</h3>
      </p>
      <!---->
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, autofocus: true, class: "form-control" %>
        </div>
        <!---->
        <div class="form-group">
          <%= f.label :content %><br />
          <%= f.text_area :content, autofocus: true, rows: 5, class: "form-control"  %>
          <small class="form-text text-muted">Improve, show Your passion!</small>
        </div>
        <!---->
        <div class="form-group">
          <div class="actions">
            <%= f.submit "Edit Status", class: "btn btn-primary"%>
          </div>
        </div>
        <!---->
        <!---->
     </div>
</div>

<% end %>

    <style>
      input, textarea, select, .uneditable-input{
        width: 100%;
      }
    </style>

app/views/statuspages/index.html.erb
<img src="/bg2.jpg" class="about-banner">

<div class="row">
	<div class="col-12 mar">
	<% if (current_user.admin?) %>
	<%= link_to "New", new_statuspage_path(@s), class: "btn btn-outline-primary btn-sm btn-wid" %>
	<% end %>
	</div>
</div>

<div class="row">
	<% for @s in @statuses %>
		<div class="col-12 mar">
			<h3> <%= @s.title %> </h3>
		</div>
		<div class="col-8">
			<p> <%= simple_format(@s.content) %> </p>
		</div>
		<div class="col-12">
			<% if (current_user.admin?) %>
			<%= link_to "Edit", edit_statuspage_path(@s), class: "btn btn-outline-primary btn-sm" %>
			<% end %>
			<% if (current_user.admin?) %>
			<%= link_to "Delete", @s, method: :delete, class: "btn btn-outline-danger btn-sm" %>
			<% end %>
		</div>
	<% end %>
</div>

<style>
	.about-banner {
		width: 1305px;
		 height: 500px;
		  margin-left: -100px;
		  margin-top: -25px;
	}
	.mar {
		margin-top: 15px;
	}
	.bac {
		background-color: pink;
	}
	.btn-wid {
		width: 200px;
	}
</style>

app/views/statuspages/new.html.erb
<%= form_for(@status) do |f| %>
 
    <!---->
<div class="row">
    <div class="col-8 offset-2">
      <p>
      <h3>Status for "Words of Love"</h3>
      </p>
      <!---->
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, autofocus: true, class: "form-control" %>
        </div>
        <!---->
        <div class="form-group">
          <%= f.label :content %><br />
          <%= f.text_area :content, autofocus: true, rows: 5, class: "form-control"  %>
          <small class="form-text text-muted">No matter what anybody tells you, words and ideas can change the world. </small>
        </div>
        <!---->
        <div class="form-group">
          <div class="actions">
            <%= f.submit "Status", class: "btn btn-primary"%>
          </div>
        </div>
        <!---->
        <!---->
     </div>
</div>

<% end %>

    <style>
      input, textarea, select, .uneditable-input{
        width: 100%;
      }
    </style>

app/views/statuspages/show.html.erb
<h1>Statuspages#show</h1>
<p>Find me in app/views/statuspages/show.html.erb</p>

app/views/statuspages/update.html.erb
<h1>Statuspages#update</h1>
<p>Find me in app/views/statuspages/update.html.erb</p>