config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :path_prefix => 'd'
  #defining the root url for the website
  root 'pages#index'

  get 'pages/show'

  get 'pages/new'

  get 'pages/create'

  get 'pages/edit'

  get 'pages/update'

  get 'pages/destroy'

  get '/user/:id' => 'users#index'

  get '/user/:id' => 'adminsongs#index'

  get '/user/:id' => 'songs#show'

  #get '/stories' => 'stories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

resources :users

#adding like option routes for songs
resources :songs do
  member do
    post 'like'
  end
end

#adding routes for comments to the songs
resources :songs do
  resources :comments
end
#adding routes for comments to comments
resources :comments do
  resources :comments
end

#resources :pages

resources :stories

#adding like option routes to the images
resources :galleries do
  member do
    post 'imagelike'
  end
end

resources :galleries do
  resources :imagecomments
end

resources :imagecomments do
  resources :imagecomments
end

resources :posts

resources :admins

resources :adminsongs

resources :adminstories

resources :adminimages

resources :aboutpages

resources :helppages

resources :termspages

resources :adspages

resources :statuspages

resources :cookiepages

resources :infopages

resources :gaboutpages

resources :ghelppages




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aboutpage.rb
class Aboutpage < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/adspage.rb
class Adspage < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable

	#belongs_to :user
	#belongs_to :song
	#validates :user_id, presence: true
	validates :content, presence: true
	#validates :song_id, presence: true
	default_scope -> { order(created_at: :desc) } #newest comments to be displayed first

end

app/models/cookiepage.rb
class Cookiepage < ApplicationRecord
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord

  has_attached_file :gallery_image, styles: { medium: "200x200"}
  validates_attachment_content_type :gallery_image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest image to be displayed first

  has_many :imagecomments, dependent: :destroy, as: :commentable
  has_many :imagelikes, dependent: :destroy


  def image_thumbs_up_total
    self.imagelikes.where(imagelike: true).size
  end
  
  def image_thumbs_down_total
    self.imagelikes.where(imagelike: false).size    
  end

end

app/models/helppage.rb
class Helppage < ApplicationRecord
  belongs_to :user
end

app/models/imagecomment.rb
class Imagecomment < ApplicationRecord

	belongs_to :commentable, polymorphic: true
	has_many :imagecomments, as: :commentable

	#belongs_to :user
	#belongs_to :song
	#validates :user_id, presence: true
	validates :content, presence: true
	#validates :song_id, presence: true
	default_scope -> { order(created_at: :desc) } #newest comments to be displayed first

end

app/models/imagelike.rb
class Imagelike < ApplicationRecord
  belongs_to :user
  belongs_to :gallery

  validates_uniqueness_of :user, scope: :gallery 

end

app/models/infopage.rb
class Infopage < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :song

  validates_uniqueness_of :user, scope: :song

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest songs to be displayed first

  has_many :comments, dependent: :destroy, as: :commentable
  has_many :likes, dependent: :destroy

  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end

end

app/models/statuspage.rb
class Statuspage < ApplicationRecord
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  
  #adding the paperclip dependencies to the stories page in order to upload images to the stories
  has_attached_file :story_image, styles: { large: "600x600>", medium: "300x300", thumb: "100x100>" }
  validates_attachment_content_type :story_image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest story to be displayed first


end

app/models/termspage.rb
class Termspage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :user_image, styles: { medium: "200x200", thumb: "85x85>" }
         validates_attachment_content_type :user_image, content_type: /\Aimage\/.*\z/

         has_attached_file :profile_image, styles: { medium: "200x200", thumb: "85x85>" }
         validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\z/

         validates :description, presence: true, length: { maximum: 140 }

         has_many :songs, dependent: :destroy # remove a user's posts if his account is deleted.
         has_many :stories, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :galleries, dependent: :destroy
         has_many :imagelikes, dependent: :destroy


         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower

         # helper methods
         
         # follow another user
         def follow(other)
           active_relationships.create(followed_id: other.id)
         end
         
         # unfollow a user
         def unfollow(other)
           active_relationships.find_by(followed_id: other.id).destroy
         end
         
         # is following a user?
         def following?(other)
           following.include?(other)
         end
end

app/controllers/adminsongs_controller.rb
class AdminsongsController < ApplicationController

  before_action :require_login, only: [:index, :new, :create, :edit, :update, :destroy, :show, :like]

  before_action :admin_user, only: [:index, :new, :create, :edit, :update, :destroy, :show, :like]
  
  def index
    @users = User.all

    @user = User.find_by_username(params[:id])

    #@songs = Song.all

    @stories = Story.all

    @images = Gallery.all
    #@toFollow = User.all.last(5)
  end

  def show
    @songs = Song.all.where("user_id = ?", User.find_by_username(params[:id]))
    #@toFollow = User.all.last(5)
    @trendsongs = Song.all.last(5)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def admin_user
      redirect_to posts_path unless current_user.admin?
    end

    def require_login
      if !user_signed_in?
          redirect_to root_path
      end
    end

end

app/helpers/adminsongs_helper.rb
module AdminsongsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/adminsongs/create.html.erb
<h1>Adminsongs#create</h1>
<p>Find me in app/views/adminsongs/create.html.erb</p>

app/views/adminsongs/destroy.html.erb
<h1>Adminsongs#destroy</h1>
<p>Find me in app/views/adminsongs/destroy.html.erb</p>

app/views/adminsongs/edit.html.erb
<h1>Adminsongs#edit</h1>
<p>Find me in app/views/adminsongs/edit.html.erb</p>

app/views/adminsongs/new.html.erb
<h1>Adminsongs#new</h1>
<p>Find me in app/views/adminsongs/new.html.erb</p>

app/views/adminsongs/show.html.erb
<div class="row">

	<div class="col-3">
		<div class="card border-secondary mb-1">
			<%= image_tag User.find_by_username(params[:id]).profile_image.url, :size=>"253x125" %>
  			<div class="card-body">			
  				<div class="row">
  				<!--adding user informations, avatar image and usernema as well as stats-->
                <div class="col-2">
                	<%= image_tag User.find_by_username(params[:id]).user_image.url, :size=>"85x85" %>
                </div>
                <div class="col-10"><h5 style="text-align: center; margin-top: 10px; margin-left: 55px;"> <%= User.find_by_username(params[:id]).username %></h5></div>
                </div>
                <div class="row" style="margin-top: 5px;">
                  <div class="col-6" style="font-size: 80%; opacity: 0.7;">SONGS<br>
                    <h6 style="color: #0084B4; font-size: 200%;">
                    	<%= User.find_by_username(params[:id]).songs.count %>
                    </h6>
                  </div>
                  <div class="col-6" style="font-size: 80%; opacity: 0.7;">FOLLOWERS<br>
                    <h6 style="color: #0084B4; font-size: 200%;">
                    	<%= User.find_by_username(params[:id]).followers.count %>
                    </h6>
                  </div>                
            	</div>
			</div>
		</div>

		<div class="card border-secondary mb-1">
  			<div class="card-body">
			<h5 style="color: grey; font-size: 125%;">Trending Songs</h5>
			<% for @t in @trendsongs%>
              <a href="<%= song_path(@t) %>" class="trendy-col"><%= @t.title %></a><br>
              <br>
            <% end %>			
			</div>
		</div>
	</div>

	<div class="col-6">
		<% for @s in @songs %>
		<div class="card border-secondary mb-1">
			<div class="card-header">
				<div class="col-1">
					<%= image_tag User.find(@s.user_id).user_image.url, :size=>"50x50" %>
				</div>
				<div class="col-11 text-muted">
					<a href="/user/<%= User.find(@s.user_id).username %>" class="info-col">
						<%= User.find(@s.user_id).username %>							
					</a> 
					- <%= @s.created_at.to_formatted_s(:short) %>
				</div>
			</div>
  			<div class="card-body">
  			<h4 class="card-title">
  				<a href="<%= song_path(@s) %>" class="link-col"><%= @s.title %></a>
  			</h4>
			<p class="card-text"><%= simple_format(@s.content) %></p>
			</div>

			<div class="card-footer text-muted">
				<!--Time: <%= @s.created_at.to_formatted_s(:short) %>-->
			    <!--<%= time_ago_in_words(@s.created_at) %> ago-->
			    <div class="col-12">
        			<div class="row">

			            <div class="col-3" id="song_like">
			            	<%= render partial: '/components/song_like' %>
			            </div>

			            <div class="col-3" id="song_dislike">
			                <%= render partial: '/components/song_dislike' %>
			            </div>

			            <div class="col-4" id="song_comment">
			            	<%= render partial: '/components/song_comment' %>
			            </div>

			        </div>
			    </div>
			</div>

		</div>
		<% end %>
	</div>

	<div class="col-3">
		
	</div>

</div>

app/views/adminsongs/update.html.erb
<h1>Adminsongs#update</h1>
<p>Find me in app/views/adminsongs/update.html.erb</p>